local Vector = require('src.vector2')
local Line = require('src.Line')

describe("Line tests", function()
    it("should identify crossing lines", function()
        local line1 = Line.new(Vector.new(0, 0), Vector.new(1, 0))
        local line2 = Line.new(Vector.new(0, 0), Vector.new(-1, 0))
        local line3 = Line.new(Vector.new(0, 0), Vector.new(0, 1))
        local line4 = Line.new(Vector.new(0, 0), Vector.new(0, -1))
        
        local line5 = Line.new(Vector.new(0, 1), Vector.new(1, 0))
        local line6 = Line.new(Vector.new(0, 1), Vector.new(1, 0.00001))
        local line7 = Line.new(Vector.new(0, 1), Vector.new(1, -0.00001))

        assert.is_not_true(line1:lineCollision(line5))
        assert.is_not_true(line2:lineCollision(line5))
        assert.is_true(line1:lineCollision(line6))
        assert.is_true(line2:lineCollision(line6))
        assert.is_true(line1:lineCollision(line7))
        assert.is_true(line2:lineCollision(line7))
        assert.is_true(line3:lineCollision(line6))
        assert.is_true(line4:lineCollision(line6))
        assert.is_true(line3:lineCollision(line7))
        assert.is_true(line4:lineCollision(line7))
    end)
end)