local Vector = require('src.vector2')
local Rect = require('src.rect')

describe("AABB Rectangle tests", function()
    it("should identify overlapping AABB rectangles", function()
        local rect1 = Rect.new(Vector.new(0, 0), Vector.new(10, 10))
        local rect2 = Rect.new(Vector.new(9, 9), Vector.new(2, 2))
        local rect3 = Rect.new(Vector.new(11, 11), Vector.new(2, 2))
        local rect4 = Rect.new(Vector.new(10.0001, 10), Vector.new(2, 2))
        local rect5 = Rect.new(Vector.new(-2, -2), Vector.new(1.99, 1.99))
        local rect6 = Rect.new(Vector.new(11, 11), Vector.new(-1, -1))
        assert.is_true(rect1:rectCollision(rect2))
        assert.is_not_true(rect1:rectCollision(rect3))
        assert.is_not_true(rect1:rectCollision(rect4))
        assert.is_not_true(rect1:rectCollision(rect5))
        assert.is_not_true(rect1:rectCollision(rect6))
    end)
end)